services:
  zeus-collector:
    build:
      context: .
      args:
        PBS_REPO_KEY_URL: ${PBS_REPO_KEY_URL}
        PBS_SSH_USER: ${PBS_USER}
        PBS_SSH_PASSWORD: ${PBS_PASSWORD}
        PBS_KRB_CONF_HOST: ${PBS_KRB_CONF_HOST}
        PBS_CONF_HOST: ${PBS_CONF_HOST}
    env_file:
      - .env
    networks:
      - zeus-collector-net
      - resource-manager-common

networks:
  zeus-collector-net:
    driver: bridge
  resource-manager-common:
    external: true
    name: metaproject-zeus_common