services:
  zeus-collector:
    build:
      context: .
      args:
        PBS_REPO_KEY_URL: ${PBS_REPO_KEY_URL}
        PBS_SSH_USER: ${PBS_USER}
        PBS_SSH_PASSWORD: ${PBS_PASSWORD}
        PBS_KRB_CONF_HOST: ${PBS_KRB_CONF_HOST}
        PBS_CONF_HOST: ${PBS_CONF_HOST}
    env_file:
      - .env
    restart: unless-stopped
    networks:
      - zeus-collector-net

networks:
  zeus-collector-net:
    driver: bridge